wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724826740
    t:
      1:
      - 49
      - 51
      - 55
      2:
      - 49
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.12.4
      5: 0.17.7
      8:
      - 5
      13: darwin-x86_64
